package resource

const (
	BrowseNodeInfoBrowseNodes                        = "BrowseNodeInfo.BrowseNodes"
	BrowseNodeInfoBrowseNodesAncestor                = "BrowseNodeInfo.BrowseNodes.Ancestor"
	BrowseNodeInfoBrowseNodesSalesRank               = "BrowseNodeInfo.BrowseNodes.SalesRank"
	BrowseNodeInfoWebsiteSalesRank                   = "BrowseNodeInfo.WebsiteSalesRank"
	BrowseNodesAncestor                              = "BrowseNodes.Ancestor"
	BrowseNodesChildren                              = "BrowseNodes.Children"
	ImagesPrimarySmall                               = "Images.Primary.Small"
	ImagesPrimaryMedium                              = "Images.Primary.Medium"
	ImagesPrimaryLarge                               = "Images.Primary.Large"
	ImagesVariantsSmall                              = "Images.Variants.Small"
	ImagesVariantsMedium                             = "Images.Variants.Medium"
	ImagesVariantsLarge                              = "Images.Variants.Large"
	ItemInfo                                         = "ItemInfo"
	OffersListingsAvailabilityMaxOrderQuantity       = "Offers.Listings.Availability.MaxOrderQuantity"
	OffersListingsAvailabilityMessage                = "Offers.Listings.Availability.Message"
	OffersListingsAvailabilityMinOrderQuantity       = "Offers.Listings.Availability.MinOrderQuantity"
	OffersListingsAvailabilityType                   = "Offers.Listings.Availability.Type"
	OffersListingsCondition                          = "Offers.Listings.Condition"
	OffersListingsConditionSubCondition              = "Offers.Listings.Condition.SubCondition"
	OffersListingsDeliveryInfoIsAmazonFulfilled      = "Offers.Listings.DeliveryInfo.IsAmazonFulfilled"
	OffersListingsDeliveryInfoIsFreeShippingEligible = "Offers.Listings.DeliveryInfo.IsFreeShippingEligible"
	OffersListingsDeliveryInfoIsPrimeEligible        = "Offers.Listings.DeliveryInfo.IsPrimeEligible"
	OffersListingsDeliveryInfoShippingCharges        = "Offers.Listings.DeliveryInfo.ShippingCharges"
	OffersListingsIsBuyBoxWinner                     = "Offers.Listings.IsBuyBoxWinner"
	OffersListingsLoyaltyPointsPoints                = "Offers.Listings.LoyaltyPoints.Points"
	OffersListingsMerchantInfo                       = "Offers.Listings.MerchantInfo"
	OffersListingsPrice                              = "Offers.Listings.Price"
	OffersListingsProgramEligibilityIsPrimeExclusive = "Offers.Listings.ProgramEligibility.IsPrimeExclusive"
	OffersListingsProgramEligibilityIsPrimePantry    = "Offers.Listings.ProgramEligibility.IsPrimePantry"
	OffersListingsPromotions                         = "Offers.Listings.Promotions"
	OffersListingsSavingBasis                        = "Offers.Listings.SavingBasis"
	OffersSummariesHighestPrice                      = "Offers.Summaries.HighestPrice"
	OffersSummariesLowestPrice                       = "Offers.Summaries.LowestPrice"
	OffersSummariesOfferCount                        = "Offers.Summaries.OfferCount"
	ParentASIN                                       = "ParentASIN"
	SearchRefinements                                = "SearchRefinements"
	VariationSummaryPriceHighestPrice                = "VariationSummary.Price.HighestPrice"
	VariationSummaryPriceLowestPrice                 = "VariationSummary.Price.LowestPrice"
	VariationSummaryVariationDimension               = "VariationSummary.VariationDimension"
)
