package api

type Resource string

const (
	BrowseNodeInfoBrowseNodes                        Resource = "BrowseNodeInfo.BrowseNodes"
	BrowseNodeInfoBrowseNodesAncestor                Resource = "BrowseNodeInfo.BrowseNodes.Ancestor"
	BrowseNodeInfoBrowseNodesSalesRank               Resource = "BrowseNodeInfo.BrowseNodes.SalesRank"
	BrowseNodeInfoWebsiteSalesRank                   Resource = "BrowseNodeInfo.WebsiteSalesRank"
	BrowseNodesAncestor                              Resource = "BrowseNodes.Ancestor"
	BrowseNodesChildren                              Resource = "BrowseNodes.Children"
	ImagesPrimarySmall                               Resource = "Images.Primary.Small"
	ImagesPrimaryMedium                              Resource = "Images.Primary.Medium"
	ImagesPrimaryLarge                               Resource = "Images.Primary.Large"
	ImagesVariantsSmall                              Resource = "Images.Variants.Small"
	ImagesVariantsMedium                             Resource = "Images.Variants.Medium"
	ImagesVariantsLarge                              Resource = "Images.Variants.Large"
	ItemInfoResource                                 Resource = "ItemInfo"
	OffersListingsAvailabilityMaxOrderQuantity       Resource = "Offers.Listings.Availability.MaxOrderQuantity"
	OffersListingsAvailabilityMessage                Resource = "Offers.Listings.Availability.Message"
	OffersListingsAvailabilityMinOrderQuantity       Resource = "Offers.Listings.Availability.MinOrderQuantity"
	OffersListingsAvailabilityType                   Resource = "Offers.Listings.Availability.Type"
	OffersListingsCondition                          Resource = "Offers.Listings.Condition"
	OffersListingsConditionSubCondition              Resource = "Offers.Listings.Condition.SubCondition"
	OffersListingsDeliveryInfoIsAmazonFulfilled      Resource = "Offers.Listings.DeliveryInfo.IsAmazonFulfilled"
	OffersListingsDeliveryInfoIsFreeShippingEligible Resource = "Offers.Listings.DeliveryInfo.IsFreeShippingEligible"
	OffersListingsDeliveryInfoIsPrimeEligible        Resource = "Offers.Listings.DeliveryInfo.IsPrimeEligible"
	OffersListingsDeliveryInfoShippingCharges        Resource = "Offers.Listings.DeliveryInfo.ShippingCharges"
	OffersListingsIsBuyBoxWinner                     Resource = "Offers.Listings.IsBuyBoxWinner"
	OffersListingsLoyaltyPointsPoints                Resource = "Offers.Listings.LoyaltyPoints.Points"
	OffersListingsMerchantInfo                       Resource = "Offers.Listings.MerchantInfo"
	OffersListingsPrice                              Resource = "Offers.Listings.Price"
	OffersListingsProgramEligibilityIsPrimeExclusive Resource = "Offers.Listings.ProgramEligibility.IsPrimeExclusive"
	OffersListingsProgramEligibilityIsPrimePantry    Resource = "Offers.Listings.ProgramEligibility.IsPrimePantry"
	OffersListingsPromotions                         Resource = "Offers.Listings.Promotions"
	OffersListingsSavingBasis                        Resource = "Offers.Listings.SavingBasis"
	OffersSummariesHighestPrice                      Resource = "Offers.Summaries.HighestPrice"
	OffersSummariesLowestPrice                       Resource = "Offers.Summaries.LowestPrice"
	OffersSummariesOfferCount                        Resource = "Offers.Summaries.OfferCount"
	ParentASIN                                       Resource = "ParentASIN"
	SearchRefinements                                Resource = "SearchRefinements"
	VariationSummaryPriceHighestPrice                Resource = "VariationSummary.Price.HighestPrice"
	VariationSummaryPriceLowestPrice                 Resource = "VariationSummary.Price.LowestPrice"
	VariationSummaryVariationDimension               Resource = "VariationSummary.VariationDimension"
)
